### ISSUE TITLE
Did you get this submitted to Alpine repository?

### ISSUE THREAD

**Issue by rfay** [Flowman/pxc-alpine#1]
I'm needing xtrabackup. Would love to hear that you've submitted it to Alpine. Thanks!

**Comment by Flowman** [comment]
Yes it was submitted and declined. Unfortunately I'm not a C dev so could not fix the issue they wanted to get fixed.

**Comment by rfay** [comment]
Thanks; Recently ended up using mariabackup, bundled with all mariadb versions, and it's working great.
